title: Sophia Boris El Kerdini
description: > # this means to ignore newlines until "baseurl:"
  Je m’appelle Sophia. Mon métier est l’écriture. Ce qui alimente mes écrits ? L’Humain.
  La complexité de ses émotions, la fragilité de ses idéaux
  et les contradictions qui l’habitent sans porter atteinte à son bon sens.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sophiaboriselkerdini.com/" # the base hostname & protocol for your site
cover: /assets/images/covers/cover.png

# Build settings
markdown: kramdown
permalink: /:categories/:title.html
highlighter: null
sass:
    sass_dir: assets/_sass
    #style: compressed

plugins:
  - jekyll-autoprefixer

exclude: ["README.md"]

# Collcetions
collections:
  categories:
    output: true
    permalink: /:collection/:name
  books:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: categories
    values:
      layout: category

keywords:
    - podcast
    - programming
    - maroc
    - morocco
    - codewatay
    - لكود وأتاي
