title: Sophia Boris El Kerdini
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:categories/:title.html
highlighter: null
sass:
    sass_dir: assets/_sass
    #style: compressed

# Collcetions
collections:
  categories:
    output: true
    permalink: /:collection/:name
  books:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: categories
    values:
      layout: category

plugins:
  - jekyll-autoprefixer
